function gx-complete() {
    _values $(gcloud projects list | awk '{print $1}')
}

function gx() {
    project="$1"
    if [ -z "$project" ]; then
        line=$(gcloud projects list | peco)
        project=$(echo "${line}" | awk '{print $1}')
    else
        line=$(gcloud projects list | grep "$project")
    fi
    echo "gcloud config set project \"${project}\""
    gcloud config set project "${project}"
}

compdef gx-complete gx
